language: csharp
mono: none
dotnet: 2.1

jobs:
  include: 
    - stage: JumpPuzzle
      install:
        - dotnet restore jumpPuzzle
      script:
        - dotnet build jumpPuzzle
      
    - stage: ER-Net
      install:
        - dotnet restore ER-Net/ER_NET
      script:
        - dotnet build ER-Net/ER_NET
        
    - stage: ER-Net tests
      install:
        - cd ER-Net/ER_NET
        - dotnet restore 
        - dotnet add package xunit.runners -v 1.9.2 --package-directory testrunner
      script:
        - msbuild /p:Configuration=Release ER_NET.sl
        - dotnet ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./ER_NET_tests/bin/Release/netcoreapp2.1/ER_NET_tests.dll
