language: csharp
mono: none
dotnet: 2.1

jobs:
  include: 
    - stage: JumpPuzzle
      install:
        - dotnet restore jumpPuzzle
      script:
        - dotnet build jumpPuzzle
      
    - stage: ER-Net
      install:
        - dotnet restore ER-Net/ER_NET
      script:
        - dotnet build ER-Net/ER_NET
        
    - stage: ER-Net tests
      install:
        - dotnet restore ER-Net/ER_NET
        - dotnet add xunit.runners -Version 1.9.2 -OutputDirectory testrunner
      script:
        - msbuild /p:Configuration=Release ER-Net/ER_NET/ER_NET.sl
        - dotnet .ER-Net/ER_NET/testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe .ER-Net/ER_NET/ER_NET_tests/bin/Release/netcoreapp2.1/ER_NET_tests.dll
