language: csharp
mono: none
dotnet: 2.1

jobs:
  include: 
    -stage: JumpPuzzle
    install:
      - dotnet restore jumpPuzzle
    script:
      - dotnet build jumpPuzzle
      
    -stage: ER-Net
    install:
      -dotnet restore ER-Net/ER_NET
    script:
      -dotnet build ER-Net/ER_NET
