language: csharp
mono: none
dotnet: 2.1

jobs:
  include: 
    - stage: JumpPuzzle
      install:
        - cd jumpPuzzle
        - dotnet restore
      script:
        - dotnet build
      
    - stage: ER-Net
      install:
        - cd ER-Net/ER_NET
        - dotnet restore
      script:
        - dotnet build
        
    - stage: ER-Net tests
      install:
        - cd ER-Net/ER_NET
        - dotnet restore 
        - cd ER_NET_tests
        - dotnet add package xunit.runners -v 1.9.2 --package-directory testrunner
        - cd ../
      script:
        - dotnet build --configuration Release
        - dotnet run ./ER_NET_tests/testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./ER_NET_tests/bin/Release/netcoreapp2.1/ER_NET_tests.dll
